"""Citation-grounded answer generation engine for IP-SAKTI Sahayak."""

import json
import logging
import os
from typing import Any

from pydantic import BaseModel, Field

from src.config import config
from src.pipeline.providers import BaseLLMClient, get_llm_client

logger = logging.getLogger("ip_sakti.pipeline.answer_generator")

SYSTEM_PROMPT = """You are an expert Intellectual Property and Traditional Knowledge legal advisor for the IP-SAKTI Sahayak system.
Your task is to generate a precise, clear advisory response for the user's query based ONLY on the retrieved legal corpus documents provided below.

CRITICAL RULES:
1. You may ONLY use facts from the provided documents. Do NOT use your training knowledge. If the documents don't answer the question, say so.
2. Every legal claim or factual statement MUST have an inline citation marker, e.g. [1], [2].
3. Inline markers must be numbered consecutively starting from [1] and map directly to the items in the "citations" list in 1-to-1 correspondence ([1] -> citations[0], [2] -> citations[1]).
4. Each citation MUST contain the accurate "doc_id", "source_url", "doc_type", "section", and "date_retrieved" matching the provided document chunk. Do NOT invent doc_ids.
5. The "disclaimer" field MUST be the exact mandatory disclaimer text provided.
6. Return a valid JSON object matching the requested schema.
"""


class Citation(BaseModel):
    """Citation schema linking generated statements directly to corpus documents."""

    doc_id: str = Field(description="Unique document ID from the corpus manifest")
    source_url: str = Field(description="Official source URL of the document")
    doc_type: str = Field(
        description="Document type (e.g. statute, policy, case_study)"
    )
    section: str = Field(description="Specific section, rule, or provision cited")
    date_retrieved: str = Field(description="Date the document was retrieved")


class GeneratorOutput(BaseModel):
    """Structured output generated by the Answer Generator stage."""

    answer: str = Field(
        description="Citation-grounded advisory text containing inline citation markers like [1], [2]"
    )
    citations: list[Citation] = Field(
        description="Ordered list of source citations mapped to inline markers"
    )
    abs_flag: bool = Field(
        description="Indicates whether Access and Benefit Sharing (ABS) compliance applies"
    )
    disclaimer: str = Field(description="Mandatory legal disclaimer text")


class AnswerGenerator:
    """Citation-grounded LLM answer generator adhering strictly to retrieved corpus chunks."""

    def __init__(
        self,
        api_key: str | None = None,
        model_name: str | None = None,
        manifest_path: str | None = None,
        temperature: float | None = None,
        max_output_tokens: int | None = None,
        llm_client: BaseLLMClient | None = None,
    ) -> None:
        """Initializes the Answer Generator with provider configuration.

        Args:
            api_key: Optional API key override.
            model_name: Optional model name override.
            manifest_path: Path to corpus manifest JSON.
            temperature: LLM generation temperature.
            max_output_tokens: Max output token limit.
            llm_client: Optional pre-configured BaseLLMClient instance.
        """
        self.api_key = api_key if api_key is not None else config.GEMINI_API_KEY
        self.model_name = model_name if model_name is not None else config.GEMINI_MODEL
        self.manifest_path = manifest_path or config.CORPUS_MANIFEST_PATH
        self.temperature = (
            temperature if temperature is not None else config.GEMINI_TEMPERATURE
        )
        self.max_output_tokens = (
            max_output_tokens
            if max_output_tokens is not None
            else config.GEMINI_MAX_OUTPUT_TOKENS
        )
        if (
            self.model_name
            and "2.5" in self.model_name
            and self.max_output_tokens <= 2048
        ):
            self.max_output_tokens = 8192

        if llm_client is not None:
            self.client = llm_client
        else:
            if config.LLM_PROVIDER == "gemini":
                self.client = get_llm_client(
                    "gemini",
                    api_key=self.api_key,
                    model_name=self.model_name,
                    temperature=self.temperature,
                    max_output_tokens=self.max_output_tokens,
                )
            else:
                self.client = get_llm_client(
                    temperature=self.temperature,
                    max_output_tokens=self.max_output_tokens,
                )

        # Expose model attribute for backward compatibility with existing test mocks
        self.model = getattr(self.client, "model", self.client)

    def _get_known_manifest_doc_ids(self) -> set[str]:
        """Loads all valid doc_ids from the corpus manifest if available."""
        doc_ids: set[str] = set()
        if os.path.exists(self.manifest_path):
            try:
                with open(self.manifest_path, "r", encoding="utf-8") as f:
                    manifest_data = json.load(f)
                if isinstance(manifest_data, list):
                    for item in manifest_data:
                        if isinstance(item, dict) and "doc_id" in item:
                            doc_ids.add(item["doc_id"])
            except Exception as e:  # noqa: BLE001
                logger.warning(
                    "Could not read corpus manifest from %s: %s", self.manifest_path, e
                )
        return doc_ids

    def _format_context(self, chunks: list[dict[str, Any]]) -> str:
        """Formats retrieved chunks into structured context blocks for the prompt."""
        context_blocks = []
        for i, chunk in enumerate(chunks, start=1):
            meta = chunk.get("metadata", {})
            doc_id = chunk.get("doc_id") or meta.get("doc_id", "unknown")
            section = chunk.get("section") or meta.get("section", "N/A")
            doc_type = (
                chunk.get("document_type")
                or chunk.get("doc_type")
                or meta.get("document_type", "statute")
            )
            source_url = chunk.get("source_url") or meta.get("source_url", "")
            date_retrieved = chunk.get("date_retrieved") or meta.get(
                "date_retrieved", ""
            )
            content = (
                chunk.get("content") or chunk.get("text") or chunk.get("snippet", "")
            )

            context_blocks.append(
                f"--- Document [{i}] ---\n"
                f"doc_id: {doc_id}\n"
                f"section: {section}\n"
                f"doc_type: {doc_type}\n"
                f"source_url: {source_url}\n"
                f"date_retrieved: {date_retrieved}\n"
                f"content:\n{content}\n"
            )
        return "\n".join(context_blocks)

    def _fallback_abstention(
        self, abs_flag: bool = False, message: str | None = None
    ) -> GeneratorOutput:
        """Constructs a clean abstention output on generation or validation failure."""
        return GeneratorOutput(
            answer=message or config.ABSTENTION_MESSAGE,
            citations=[],
            abs_flag=abs_flag,
            disclaimer=config.DISCLAIMER_TEXT,
        )

    def generate_conversational(
        self, query: str, conversation_history: list[dict[str, str]] | None = None
    ) -> GeneratorOutput:
        """Handles conversational queries (e.g. greetings) without strict RAG chunks."""
        prompt = (
            "You are IP-SAKTI Sahayak, an expert IP legal assistant for Ayurveda, ABS compliance, and Traditional Knowledge in India.\n"
            f'The user said: "{query}"\n\n'
            "Respond politely and conversationally in 1-2 sentences. "
            "If they are greeting you, greet them back and ask how you can help them with their Ayurveda IP queries."
        )

        try:
            answer = self.client.generate_chat(
                prompt=prompt,
                conversation_history=conversation_history,
                temperature=0.5,
                max_tokens=300,
                timeout=config.GEMINI_REQUEST_TIMEOUT,
            )
            answer_text = (
                str(answer).strip()
                if answer
                else "Hello! How can I help you with Ayurveda IP today?"
            )
            return GeneratorOutput(
                answer=answer_text,
                citations=[],
                abs_flag=False,
                disclaimer=config.DISCLAIMER_TEXT,
            )
        except Exception as e:  # noqa: BLE001
            logger.error("Failed to generate conversational response: %s", e)
            return GeneratorOutput(
                answer="Hello! How can I help you with Ayurveda IP today?",
                citations=[],
                abs_flag=False,
                disclaimer=config.DISCLAIMER_TEXT,
            )

    def generate_refusal(self, query: str) -> str:
        """Generates a dynamic, polite refusal for out-of-domain queries using the LLM.

        Args:
            query: The user's original query.

        Returns:
            A string containing a context-aware polite refusal, or the static fallback message if the LLM fails.
        """
        refusal_prompt = (
            "You are IP-SAKTI Sahayak, an elite Intellectual Property and Traditional Knowledge legal assistant.\n"
            f'The user asked: "{query}"\n\n'
            "This query is completely outside the scope of Indian Intellectual Property, Ayurveda, or statutory compliance. "
            "Write a brief (1-2 sentences), polite refusal explaining that as the IP-SAKTI Sahayak, you are specifically designed to assist with IP strategy, patentability, ABS compliance, and traditional knowledge, and therefore cannot answer this question. "
            "Do NOT attempt to answer the question itself under any circumstances."
        )

        try:
            res = self.client.generate_text(
                refusal_prompt,
                temperature=0.3,
                max_tokens=300,
                timeout=config.GEMINI_REQUEST_TIMEOUT,
            )
            if res and res.strip():
                return res.strip()
            return config.ABSTENTION_MESSAGE
        except Exception as e:  # noqa: BLE001
            logger.warning(
                "Could not generate dynamic refusal (%s); using standard refusal.", e
            )
            return (
                "I cannot assist with this query as IP-SAKTI Sahayak is specifically scoped to Indian IP Law, "
                "Ayurveda formulations, and Biological Diversity compliance. Please consult a specialist for this domain."
            )

    def generate(
        self,
        query: str,
        chunks: list[dict[str, Any]] | None,
        product_category: str | None = None,
        abs_flag: bool = False,
        conversation_history: list[dict[str, str]] | None = None,
    ) -> GeneratorOutput:
        """Generates a citation-grounded answer based strictly on retrieved chunks.

        Args:
            query: User's original or cleaned question.
            chunks: List of retrieved legal corpus chunks from Retriever / Confidence Gate.
            product_category: Classified Ayurveda category.
            abs_flag: Whether ABS clearance is flagged for the query.
            conversation_history: Optional previous multi-turn conversation messages.

        Returns:
            GeneratorOutput with answer, citations, abs_flag, and mandatory disclaimer.
        """
        if not chunks:
            logger.info("AnswerGenerator: No chunks provided, returning abstention.")
            return self._fallback_abstention(abs_flag=abs_flag)

        context_text = self._format_context(chunks)
        category_header = (
            f"Product Category: {product_category}\n" if product_category else ""
        )

        full_prompt = (
            f"{SYSTEM_PROMPT}\n\n"
            f"{category_header}"
            f"Retrieved Legal Documents:\n{context_text}\n"
            f"User Question: {query}\n\n"
            f'Mandatory Disclaimer text to include exactly: "{config.DISCLAIMER_TEXT}"'
        )

        try:
            if conversation_history:
                result = self.client.generate_chat(
                    prompt=full_prompt,
                    conversation_history=conversation_history,
                    temperature=self.temperature,
                    max_tokens=self.max_output_tokens,
                    timeout=config.GEMINI_REQUEST_TIMEOUT,
                    response_schema=GeneratorOutput,
                )
            else:
                result = self.client.generate_structured(
                    prompt=full_prompt,
                    response_schema=GeneratorOutput,
                    temperature=self.temperature,
                    max_tokens=self.max_output_tokens,
                    timeout=config.GEMINI_REQUEST_TIMEOUT,
                )

            if not result or not isinstance(result, GeneratorOutput):
                logger.warning(
                    "AnswerGenerator: Empty or invalid response from LLM provider."
                )
                return self._fallback_abstention(abs_flag=abs_flag)

            # Enforce exact mandatory disclaimer text
            result.disclaimer = config.DISCLAIMER_TEXT
            result.abs_flag = result.abs_flag or abs_flag

            # Validate citations against manifest and retrieved chunks (P0 requirement)
            allowed_doc_ids = self._get_known_manifest_doc_ids()
            for chunk in chunks:
                c_meta = chunk.get("metadata", {})
                cid = chunk.get("doc_id") or c_meta.get("doc_id")
                if cid:
                    allowed_doc_ids.add(cid)

            for citation in result.citations:
                if allowed_doc_ids and citation.doc_id not in allowed_doc_ids:
                    logger.error(
                        "P0 Bug: Citation doc_id '%s' does not exist in manifest or retrieved chunks! Falling back to abstention.",
                        citation.doc_id,
                    )
                    return self._fallback_abstention(abs_flag=abs_flag)

            return result

        except Exception as e:
            err_msg = str(e).lower()
            if any(
                k in err_msg
                for k in [
                    "api_key",
                    "api key",
                    "invalid api key",
                    "unauthenticated",
                    "permission denied",
                    "api key not valid",
                    "api_key_invalid",
                ]
            ):
                logger.error("AnswerGenerator API key/auth error: %s", e)
                raise RuntimeError(f"Gemini API key error: {e}") from e

            if "429" in err_msg or "quota" in err_msg or "rate limit" in err_msg:
                logger.error("AnswerGenerator hit API Rate Limit: %s", e)
                return self._fallback_abstention(
                    abs_flag=abs_flag,
                    message="Our system is currently experiencing high traffic and has hit its API rate limits. Please try again later.",
                )

            logger.error("AnswerGenerator failed: %s. Falling back to abstention.", e)
            return self._fallback_abstention(abs_flag=abs_flag)
